CREATE TABLE BLOG(
     ID_BLOG INT PRIMARY KEY,
     TITLE VARCHAR(800) NOT  NULL,
     URL VARCHAR(2000) NOT  NULL,
     THUMBNAIL VARCHAR(2000) NULL,
     CONTENTS VARCHAR(3000) NOT  NULL,
     BLOG_NAME VARCHAR(2000) NOT  NULL,
     MOD_DATE_TIME TIMESTAMP NOT  NULL,
     REG_DATE_TIME TIMESTAMP NOT  NULL,
     USE_YN VARCHAR(1) NOT  NULL,
     PRIMARY KEY (ID_BLOG)
);